from flask import Flask, jsonify

app = Flask(__name__)

DATA = [
  {
    "Timestamp": "2026-04-14 13:14:19.805000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 14:56:40.886000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 14:58:19.970000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 14:58:28.738000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 14:58:48.829000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-14 16:00:33.441000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 16:01:40.927000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 16:02:00.122000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 16:08:14.484000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-14 17:27:54.394000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-14 17:34:15.838000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-15 21:04:06.833000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-19 09:18:07.730000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-19 09:18:35.456000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-19 19:51:50.855000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 21:56:17.788000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:02:39.908000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:03:08.341000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:03:36.266000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-20 22:03:59.408000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-20 22:04:23.910000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:04:26.076000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:04:47.635000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:05:11.501000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:05:12.173000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:05:40.440000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-20 22:05:42.420000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:06:49.881000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 22:07:00.776000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-20 22:07:33.368000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya cenderung menyerah",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": "2026-04-20 22:13:42.541000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 23:25:57.453000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-20 23:50:29.888000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "30 tahun >",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 18:38:47.709000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 18:39:11.271000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 18:39:36.174000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "< 20 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya sering menunda",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 18:40:07.653000",
    "Status Anda saat ini": "Pekerja",
    "  Usia  ": "26–30 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya mudah emosi",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Lebih banyak digunakan untuk santai",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 19:38:45.118000",
    "Status Anda saat ini": "Keduanya",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-21 19:39:15.758000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Laki-laki",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya langsung kesal/marah",
    "Ketika rencana gagal  ": "Saya cepat frustrasi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Sudah selesai sebelumnya",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya tetap berusaha menyelesaikan"
  },
  {
    "Timestamp": "2026-04-28 16:12:15.068000",
    "Status Anda saat ini": "Mahasiswa",
    "  Usia  ": "20–25 tahun",
    "  Jenis kelamin  ": "Perempuan",
    "Saat menghadapi masalah  ": "Saya tetap tenang",
    "Jika ada orang melakukan kesalahan  ": "Saya mencoba memahami dulu",
    "Ketika rencana gagal  ": "Saya mencari solusi",
    "Ketika ada tugas": "Saya langsung mengerjakan",
    "Waktu luang  ": "Digunakan untuk hal produktif",
    "Mendekati deadline  ": "Baru mulai mengerjakan",
    "Saat menghadapi kesulitan  ": "Saya terus mencoba",
    "Beban kerja/tugas banyak  ": "Saya merasa kewalahan dan berhenti"
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Jenis kelamin",
    "Status Anda saat ini": "Frequency",
    "  Usia  ": "Precent",
    "  Jenis kelamin  ": "Komulatif",
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Laki-laki",
    "Status Anda saat ini": 25.0,
    "  Usia  ": 0.625,
    "  Jenis kelamin  ": 0.625,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Perempuan",
    "Status Anda saat ini": 15.0,
    "  Usia  ": 0.375,
    "  Jenis kelamin  ": 1,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "TOTAL",
    "Status Anda saat ini": 40,
    "  Usia  ": 1,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Usia",
    "Status Anda saat ini": "Frequency",
    "  Usia  ": "Precent",
    "  Jenis kelamin  ": "Komulatif",
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "< 20 tahun",
    "Status Anda saat ini": 9.0,
    "  Usia  ": 0.225,
    "  Jenis kelamin  ": 0.225,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "20–25 tahun",
    "Status Anda saat ini": 20.0,
    "  Usia  ": 0.5,
    "  Jenis kelamin  ": 0.725,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "26–30 tahun",
    "Status Anda saat ini": 10.0,
    "  Usia  ": 0.25,
    "  Jenis kelamin  ": 0.975,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "30 tahun >",
    "Status Anda saat ini": 1.0,
    "  Usia  ": 0.025,
    "  Jenis kelamin  ": 1,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "TOTAL",
    "Status Anda saat ini": 40.0,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": null,
    "Status Anda saat ini": null,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Status Anda saat ini",
    "Status Anda saat ini": "Frequency",
    "  Usia  ": "Precent",
    "  Jenis kelamin  ": "Komulatif",
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Mahasiswa",
    "Status Anda saat ini": 21.0,
    "  Usia  ": 0.525,
    "  Jenis kelamin  ": 0.525,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Pekerja",
    "Status Anda saat ini": 9.0,
    "  Usia  ": 0.225,
    "  Jenis kelamin  ": 0.75,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "Keduanya",
    "Status Anda saat ini": 10.0,
    "  Usia  ": 0.25,
    "  Jenis kelamin  ": 1,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  },
  {
    "Timestamp": "TOTAL",
    "Status Anda saat ini": 40.0,
    "  Usia  ": null,
    "  Jenis kelamin  ": null,
    "Saat menghadapi masalah  ": null,
    "Jika ada orang melakukan kesalahan  ": null,
    "Ketika rencana gagal  ": null,
    "Ketika ada tugas": null,
    "Waktu luang  ": null,
    "Mendekati deadline  ": null,
    "Saat menghadapi kesulitan  ": null,
    "Beban kerja/tugas banyak  ": null
  }
]

@app.route("/")
def home():
    return jsonify(DATA)

if __name__ == "__main__":
    app.run(debug=True)
